---
- name: Run base role
  hosts: all
  roles:
    - { role: base, tags: base, always }
  tags: always

- name: Run all other roles
  hosts: all
  roles:
    - { role: starship, tags: starship }
    - { role: nginxinc.nginx, tags: nginx }
